# Generated by Django 4.0.3 on 2022-05-16 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='add_prisonerr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('crime', models.CharField(max_length=50, null=True)),
                ('fir', models.FileField(null=True, upload_to='', verbose_name='file/')),
                ('join_date', models.DateField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('proof', models.FileField(null=True, upload_to='', verbose_name='file/')),
                ('status', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='warden_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('con_password', models.CharField(max_length=50, null=True)),
                ('experience', models.FileField(null=True, upload_to='', verbose_name='file/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='parole_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('release_reason', models.CharField(max_length=50)),
                ('parole_period', models.CharField(max_length=50)),
                ('request_status', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('prisoner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IAPS_app.add_prisonerr')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IAPS_app.warden_reg')),
            ],
        ),
        migrations.CreateModel(
            name='medical_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('con_password', models.CharField(max_length=50, null=True)),
                ('experience', models.FileField(null=True, upload_to='', verbose_name='file/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='add_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('max', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('warden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IAPS_app.warden_reg')),
            ],
        ),
        migrations.CreateModel(
            name='add_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, null=True)),
                ('week', models.IntegerField(null=True)),
                ('task_name', models.CharField(max_length=50, null=True)),
                ('dat', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('add_tas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IAPS_app.add_task')),
                ('prisoner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IAPS_app.add_prisonerr')),
            ],
        ),
        migrations.AddField(
            model_name='add_prisonerr',
            name='warden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IAPS_app.warden_reg'),
        ),
        migrations.CreateModel(
            name='add_prisoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=50)),
                ('crime', models.CharField(max_length=50)),
                ('fir', models.FileField(null=True, upload_to='', verbose_name='file/')),
                ('join_date', models.DateField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('proof', models.FileField(null=True, upload_to='', verbose_name='file/')),
                ('dob', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='add_health_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=50)),
                ('allergies', models.CharField(max_length=50)),
                ('deseases', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('bp', models.CharField(max_length=50)),
                ('medication', models.CharField(max_length=50)),
                ('reading_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('prisoner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IAPS_app.add_prisonerr')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='add_complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('complaint', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100, null=True)),
                ('action', models.CharField(max_length=50, null=True)),
                ('prisoner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IAPS_app.add_prisonerr')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IAPS_app.warden_reg')),
            ],
        ),
        migrations.CreateModel(
            name='add_attendancee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, null=True)),
                ('dat', models.DateField(null=True)),
                ('attendance', models.CharField(max_length=50)),
                ('count', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('prisoner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IAPS_app.add_prisonerr')),
            ],
        ),
    ]
